In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

C:\Users\AlokVerma\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df = pd.read_csv(r"C:\Users\AlokVerma\Desktop\ML DATA\diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
df.shape

(767, 9)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               767 non-null    int64
 1   Glucose                   767 non-null    int64
 2   BloodPressure             767 non-null    int64
 3   SkinThickness             767 non-null    int64
 4   Insulin                   767 non-null    int64
 5   BMI                       767 non-null    float64
 6   DiabetesPedigreeFunction  767 non-null    float64
 7   Age                       767 non-null    int64
 8   Outcome                   767 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,767.000000,767.000000,767.000000,767.000000,767.000000,767.000000,767.000000,767.000000,767.000000
mean,3.848761,120.930900,69.104302,20.522816,79.903520,31.994654,0.472081,33.254237,0.349413
std,3.370207,31.977581,19.368410,15.958143,115.283105,7.889095,0.331496,11.762079,0.477096
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243500,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,32.000000,32.000000,0.374000,29.000000,0.000000
75%,6.000000,140.500000,80.000000,32.000000,127.500000,36.600000,0.626500,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [7]:
df.Outcome.value_counts()

Outcome
0    499
1    268
Name: count, dtype: int64

In [8]:
X = df.iloc[:,0:8]

In [10]:
y = df.iloc[:,-1]

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc = StandardScaler()

In [14]:
X = sc.fit_transform(X)

In [19]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [35]:
len(X_test)

154

In [36]:
len(y_train)

613

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [40]:
dt = DecisionTreeClassifier().fit(X_train,y_train)

In [43]:
y_predict = dt.predict(X_test)

In [47]:
# 2. Method A: Direct score (Accuracy)
print("Accuracy:", dt.score(X_test, y_test))

Accuracy: 0.7077922077922078

In [48]:
from sklearn.ensemble import BaggingClassifier

In [49]:
beg = BaggingClassifier(estimator=DecisionTreeClassifier(),oob_score=False, n_estimators=500, random_state=0)

In [50]:
bag_clf = BaggingClassifier( DecisionTreeClassifier(), n_estimators=500,oob_score=False, max_samples=100, bootstrap=True, n_jobs=-1)

In [51]:
beg.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=500,
                  random_state=0)

In [53]:
print("Accuracy of Beg:", beg.score(X_test, y_test))

Accuracy of Beg: 0.7532467532467533

In [52]:
bag_clf.fit(X_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_samples=100,
                  n_estimators=500, n_jobs=-1)

In [54]:
print("Accuracy of Beg_clf:", bag_clf.score(X_test, y_test))

Accuracy of Beg_clf: 0.7337662337662337

In [56]:
from sklearn.svm import SVC

In [57]:
clf_svm  = BaggingClassifier(estimator=SVC(),n_estimators=10, random_state=0)

In [58]:
clf_svm.fit(X_train,y_train)

BaggingClassifier(estimator=SVC(), random_state=0)

In [59]:
print("Accuracy of Beg_svm:",  clf_svm.score(X_test, y_test))

Accuracy of Beg_svm: 0.7272727272727273

In [60]:
from sklearn.ensemble import RandomForestClassifier

In [61]:
rf_clf = RandomForestClassifier()

In [62]:
rf_clf.fit(X_train,y_train)

RandomForestClassifier()

In [63]:
print("Accuracy of rf:",  rf_clf.score(X_test, y_test))

Accuracy of Beg_svm: 0.7532467532467533

In [64]:
beg_rf = BaggingClassifier(estimator=RandomForestClassifier(),oob_score=False, n_estimators=500, random_state=0)

In [65]:
beg_rf.fit(X_train,y_train)

BaggingClassifier(estimator=RandomForestClassifier(), n_estimators=500,
                  random_state=0)

In [66]:
print("Accuracy of Beg_rf:",  beg_rf.score(X_test, y_test))

Accuracy of Beg_rf: 0.7597402597402597