In [102]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [103]:
df = pd.read_csv(r"C:\Users\AlokVerma\Desktop\ML DATA\Telco_Cusomer_Churn.csv")
df.head()

   customerID  gender  SeniorCitizen Partner  ...              PaymentMethod  MonthlyCharges TotalCharges Churn
0  7590-VHVEG  Female              0     Yes  ...           Electronic check           29.85        29.85    No
1  5575-GNVDE    Male              0      No  ...               Mailed check           56.95       1889.5    No
2  3668-QPYBK    Male              0      No  ...               Mailed check           53.85       108.15   Yes
3  7795-CFOCW    Male              0      No  ...  Bank transfer (automatic)           42.30      1840.75    No
4  9237-HQITU  Female              0      No  ...           Electronic check           70.70       151.65   Yes

[5 rows x 21 columns]

In [105]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"],errors= 'coerce' )

In [106]:
df = df.dropna()

In [107]:
df.sample()

      customerID  gender  SeniorCitizen Partner  ...            PaymentMethod  MonthlyCharges TotalCharges Churn
6893  5876-HZVZM  Female              0     Yes  ...  Credit card (automatic)            55.9       365.35   Yes

[1 rows x 21 columns]

In [108]:
df.shape

(7032, 21)

In [109]:
df.drop(columns=["customerID"], errors="ignore", inplace=True)

In [110]:
df.shape

(7032, 20)

In [111]:
df.head()

   gender  SeniorCitizen Partner Dependents  ...              PaymentMethod MonthlyCharges TotalCharges Churn
0  Female              0     Yes         No  ...           Electronic check          29.85        29.85    No
1    Male              0      No         No  ...               Mailed check          56.95      1889.50    No
2    Male              0      No         No  ...               Mailed check          53.85       108.15   Yes
3    Male              0      No         No  ...  Bank transfer (automatic)          42.30      1840.75    No
4  Female              0      No         No  ...           Electronic check          70.70       151.65   Yes

[5 rows x 20 columns]

In [112]:
# SeniorCitizen = int
# tenure = int
# MonthlyCharges = int
# TotalCharges = int

In [113]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [114]:
X = df.iloc[:,0:19]

In [115]:
y = df.iloc[:,[-1]]

In [116]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='str')

In [117]:
X = pd.get_dummies(X,columns=['gender', 'Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'],drop_first=True)

In [118]:
X

      SeniorCitizen  tenure  ...  PaymentMethod_Electronic check  PaymentMethod_Mailed check
0                 0       1  ...                            True                       False
1                 0      34  ...                           False                        True
2                 0       2  ...                           False                        True
3                 0      45  ...                           False                       False
4                 0       2  ...                            True                       False
...             ...     ...  ...                             ...                         ...
7038              0      24  ...                           False                        True
7039              0      72  ...                           False                       False
7040              0      11  ...                            True                       False
7041              1       4  ...                           False                        True
7042              0      66  ...                           False                       False

[7032 rows x 30 columns]

In [119]:
sc  = StandardScaler()

In [120]:
X = sc.fit_transform(X)

In [121]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [122]:
len(y_train)

5625

In [123]:
len(y_test)

1407

In [124]:
knn = KNeighborsClassifier()

In [125]:
knn.fit(X_train,y_train)

C:\Users\AlokVerma\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

In [127]:
y_pred = knn.predict(X_test)

In [130]:
from sklearn.metrics import confusion_matrix,f1_score,precision_score,recall_score

In [131]:
confusion_matrix(y_test,y_pred)

array([[845, 168],
       [194, 200]])

In [140]:
f1_score(y_test,y_pred,average='micro')

0.7427149964463398

In [143]:
f1_score(y_test,y_pred,average=None)

array([0.82358674, 0.52493438])

In [145]:
precision_score(y_test,y_pred,average='micro')

0.7427149964463398

In [146]:
recall_score(y_test,y_pred,average="micro")

0.7427149964463398