In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv(r"C:\Users\AlokVerma\Desktop\ML DATA\Telco_Cusomer_Churn.csv")

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.drop(columns=["customerID"],axis="columns", inplace=True)

In [6]:
df["TotalCharges"]= pd.to_numeric(df["TotalCharges"],errors="coerce")

In [7]:
df.dropna(inplace=True,how="any")

In [8]:
df = pd.get_dummies(df,drop_first=True)

In [9]:
df.Churn_Yes.value_counts()

Churn_Yes
False    5163
True     1869
Name: count, dtype: int64

In [10]:
X = df.drop(["Churn_Yes"],axis=1)
y = df["Churn_Yes"]

In [11]:
X

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,True,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,True,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,True,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,24,84.80,1990.50,True,True,True,True,False,True,...,False,True,False,True,True,False,True,False,False,True
7039,0,72,103.20,7362.90,False,True,True,True,False,True,...,False,True,False,True,True,False,True,True,False,False
7040,0,11,29.60,346.45,False,True,True,False,True,False,...,False,False,False,False,False,False,True,False,True,False
7041,1,4,74.40,306.60,True,True,False,True,False,True,...,False,False,False,False,False,False,True,False,False,True
7042,0,66,105.65,6844.50,True,False,False,True,False,False,...,False,True,False,True,False,True,True,False,False,False

In [12]:
y.head()

0    False
1    False
2     True
3    False
4     True
Name: Churn_Yes, dtype: bool

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
model_orig = LogisticRegression()

In [15]:
model_orig.fit(X_train,y_train)

C:\Users\AlokVerma\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [16]:
pred_orig = model_orig.predict(X_test)

In [17]:
accuracy_orig = accuracy_score(y_test,pred_orig)

In [18]:
accuracy_orig

0.7987936234381732

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
dt  = DecisionTreeClassifier()

In [21]:
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [22]:
dt_pred = dt.predict(X_test)

In [23]:
accuracy_score(y_test,dt_pred)

0.7238259370960792

# Applying PCA Algorithms

In [24]:
from sklearn.decomposition import PCA

In [66]:
pca = PCA(n_components = 4)

In [67]:
X_train_pcs = pca.fit_transform(X_train)
X_test_pca = pca.fit_transform(X_test)

In [68]:
explained_variance = pca.explained_variance_

print(explained_variance)

[5.19032443e+06 6.16673318e+02 8.16116356e+01 6.08029886e-01]

In [69]:
# Training the logistics Regeression

In [70]:
model_log = LogisticRegression()

In [71]:
model_log.fit(X_train_pcs,y_train)

LogisticRegression()

In [72]:
pca_pred = model_log.predict(X_test_pca)

In [73]:
pca_accuracy = accuracy_score(y_test,pca_pred)

In [74]:
pca_accuracy

0.7789745799224472

In [75]:
dt_pca = DecisionTreeClassifier()

In [76]:
dt_pca.fit(X_train_pcs,y_train)

DecisionTreeClassifier()

In [77]:
dt_pca_pred = dt_pca.predict(X_test_pca)

In [78]:
accuracy_score(y_test,dt_pca_pred)

0.7169323567427833

# lda

In [79]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [80]:
lda = LinearDiscriminantAnalysis()

In [81]:
X_train_lda = lda.fit_transform(X_train,y_train)
X_test_lda  = lda.transform(X_test)

In [82]:
lda_varaiance = lda.explained_variance_ratio_

In [83]:
lda_varaiance

array([1.])

In [84]:
model_lda = LogisticRegression()

In [85]:
model_lda.fit(X_train_lda,y_train)

LogisticRegression()

In [86]:
lda_pred = model_lda.predict(X_test_lda)

In [87]:
accuracy_score(y_test,lda_pred)

0.7979319258940112

In [88]:
dt_lda = DecisionTreeClassifier()

In [89]:
dt_lda.fit(X_train_lda,y_train)

DecisionTreeClassifier()

In [90]:
lda_dt_pred = dt_lda.predict(X_test_lda)

In [91]:
accuracy_score(y_test,lda_dt_pred)

0.7190866006031883