In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\AlokVerma\Desktop\ML DATA\Telco_Cusomer_Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"],errors = "coerce")

In [4]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7032.000000
mean        0.162147    32.371149       64.761692   2283.300441
std         0.368612    24.559481       30.090047   2266.771362
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [5]:
df.dropna(inplace=True)

In [6]:
df.shape

(7032, 21)

In [7]:
df.drop(columns=["customerID"],inplace=True)

In [8]:
X = df.iloc[:,0:19]

In [9]:
y = df.iloc[:,-1]

In [10]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='str')

In [11]:
X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents', 
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'],drop_first=True)

In [12]:
# X = X.astype("int")
# y = y.astype("int")

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
sc = StandardScaler()

In [15]:
X = sc.fit_transform(X)

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [18]:
from sklearn.ensemble import RandomForestClassifier

In [19]:
rf_clf = RandomForestClassifier()

In [20]:
rf_clf.fit(X_train,y_train)

RandomForestClassifier()

In [21]:
rf_pred = rf_clf.predict(X_test)

In [22]:
rf_clf.score(X_test,rf_pred)

1.0

In [23]:
from sklearn.metrics import r2_score,accuracy_score,f1_score

In [24]:
accuracy_score(y_test,rf_pred)

0.7897457992244722

In [25]:
f1_score(y_test,rf_pred,average='micro')

0.7897457992244722

# Apply here XgBoost

In [26]:
# y = y.replace({"No": 0, "Yes": 1})

In [27]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [28]:
import xgboost as xgb

In [29]:
from xgboost import XGBClassifier

In [33]:
clf = xgb.XGBClassifier(
    n_estimators=100,      # Number of boosting rounds
    learning_rate=0.1,     # Step size shrinkage
    max_depth=3,           # Maximum depth of the tree
    # objective='binary:logistic', # For binary classification
    random_state=42
)

In [34]:
clf.fit(X_train,y_train)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1], got ['No' 'Yes']

In [36]:
xg_pred = clf.predict(X_test)

NotFittedError: need to call fit or load_model beforehand

In [ ]:
f1_score(y_test,xg_pred,average="micro")

In [ ]:
accuracy_score(y_test,xg_pred)

In [ ]:
xg.score(X_test,xg_pred)

In [ ]:
r2_score(y_test,xg_pred)

In [37]:
y_test

2481     No
6784     No
6125    Yes
3052     No
4099     No
       ...
1118     No
4957     No
298      No
3312     No
5585    Yes
Name: Churn, Length: 2321, dtype: str

In [38]:
from sklearn.ensemble import AdaBoostClassifier

In [39]:
ada = AdaBoostClassifier()

In [40]:
ada.fit(X_train,y_train)

AdaBoostClassifier()

In [41]:
ada_pred = ada.predict(X_test)

In [42]:
accuracy_score(y_test,ada_pred)

0.8013787160706592

In [43]:
from sklearn.ensemble import GradientBoostingClassifier

In [44]:
gbc = GradientBoostingClassifier()

In [45]:
gbc.fit(X_train,y_train)

GradientBoostingClassifier()

In [46]:
gbc_pred = gbc.predict(X_test)

In [47]:
accuracy_score(y_test,gbc_pred)

0.7996553209823352